/**
 * Blueprint generation.
 *
 * This is the factory's only write path to Render. Nothing here calls an API:
 * it produces YAML, the workflow commits it, and Render's Blueprint sync
 * creates and deploys whatever changed. That means every piece of
 * infrastructure the factory has ever created is reviewable in Git, and an
 * agent cannot provision anything without a commit.
 *
 * Blueprints are generated from the agent-declared service manifest, not from
 * constants. The manifest is what the builder says it built: directories,
 * commands, health paths, env var wiring.
 */
import { factoryConfig, appRelativePath } from "../factory.config.js";
import type { AppSpec, Manifest, Service } from "./contracts.js";

// Specs written before the neutral rename did not persist their prefix.
const LEGACY_RESOURCE_PREFIX = "airo";

export interface ResourceNames {
	/** Render resource name for every manifest service, keyed by manifest name. */
	services: Map<string, string>;
	/** Render resource name for every manifest database, keyed by manifest name. */
	databases: Map<string, string>;
	/** The primary storefront, if the app has one. Reported as the app's URL. */
	web: string | null;
	/** The primary API, if the app has one. */
	api: string | null;
	/** The primary database, which an unqualified `fromDatabase` refers to. */
	db: string | null;
}

/**
 * Render resource names are unique per workspace, and the root Blueprint holds
 * every generated app at once, so the user and app names both have to be in
 * here. Components are truncated to keep the whole name within Render's limit.
 *
 * The first storefront, API, and database keep the `-web`, `-api`, and `-db`
 * names the factory has always used. Anything beyond them is named after
 * itself: the manifest allows six services and three databases, and two
 * resources that collapse onto one name silently overwrite each other in the
 * Blueprint rather than failing.
 */
export function resourceNames(spec: AppSpec): ResourceNames {
	const stem = [
		spec.resourcePrefix ?? LEGACY_RESOURCE_PREFIX,
		spec.user.slice(0, 12),
		spec.appName.slice(0, 24),
	].join("-");

	const taken = new Set<string>();
	const claim = (suffix: string): string => {
		const base = `${stem}-${suffix}`;
		let name = base;
		for (let n = 2; taken.has(name); n++) name = `${base}-${n}`;
		taken.add(name);
		return name;
	};

	const services = new Map<string, string>();
	let web: string | null = null;
	let api: string | null = null;

	for (const service of spec.manifest.services) {
		const primary =
			service.kind === "static_site" ? web === null : api === null;
		const name = claim(primary ? roleOf(service) : slugify(service.name));
		services.set(service.name, name);
		if (primary && service.kind === "static_site") web = name;
		if (primary && service.kind === "web_service") api = name;
	}

	const databases = new Map<string, string>();
	let db: string | null = null;
	for (const database of spec.manifest.databases ?? []) {
		const name = claim(db === null ? "db" : slugify(database.name));
		databases.set(database.name, name);
		db ??= name;
	}

	return { services, databases, web, api, db };
}

function roleOf(service: Service): string {
	return service.kind === "static_site" ? "web" : "api";
}

/** A manifest-supplied name, reduced to something Render accepts. */
function slugify(name: string): string {
	return (
		name
			.toLowerCase()
			.replace(/[^a-z0-9]+/g, "-")
			.replace(/^-|-$/g, "")
			.slice(0, 20) || "svc"
	);
}

/**
 * The Blueprint for one app, committed beside it. Deployable on its own by
 * pointing a new Blueprint at this path, which is how a generated app can
 * graduate out of the factory's shared Blueprint.
 */
export function appBlueprint(spec: AppSpec): string {
	const root = appRelativePath(spec.user, spec.appName);
	const names = resourceNames(spec);
	return [
		`# ${spec.user}/${spec.appName} — generated by the Vibe Code factory.`,
		`# Prompt: ${oneLine(spec.prompt)}`,
		"",
		"services:",
		...serviceBlocks(spec.manifest, root, names),
		...databaseBlocks(spec.manifest, names),
	].join("\n");
}

/**
 * The repository-root Blueprint: every generated app in one file. This is the
 * file Render watches, so appending an app to it is what deploys that app.
 * Regenerated from every apps/<user>/<app>/factory.json on each run, which is why
 * the specs are stored as JSON rather than parsed back out of YAML.
 */
export function rootBlueprint(specs: readonly AppSpec[]): string {
	const ordered = [...specs].sort((a, b) =>
		`${a.user}/${a.appName}`.localeCompare(`${b.user}/${b.appName}`),
	);

	const header = [
		"# Generated by the Vibe Code factory. Do not edit by hand.",
		"#",
		"# One Blueprint holds every app the factory has built. A run appends its",
		"# app's resources here, and Render's Blueprint sync deploys them.",
		`# Apps: ${ordered.length}`,
		"",
	];

	if (ordered.length === 0) {
		return [
			...header,
			"# No apps yet. The first run will add one.",
			"services: []",
			"",
		].join("\n");
	}

	const services: string[] = [];
	const databases: string[] = [];
	for (const spec of ordered) {
		const root = appRelativePath(spec.user, spec.appName);
		const names = resourceNames(spec);
		services.push(`  # ── ${spec.user}/${spec.appName} ${"─".repeat(20)}`);
		services.push(...serviceBlocks(spec.manifest, root, names));
		databases.push(...databaseBlocks(spec.manifest, names).slice(1));
	}

	return [
		...header,
		"services:",
		...services,
		...(databases.length > 0 ? ["databases:", ...databases] : []),
		"",
	].join("\n");
}

/* ── YAML generation from manifest ────────────────────────────────────── */

function serviceBlocks(
	manifest: Manifest,
	root: string,
	names: ResourceNames,
): string[] {
	const lines: string[] = [];

	for (const service of manifest.services) {
		const resourceName = names.services.get(service.name);
		if (!resourceName) continue;
		lines.push(...singleServiceBlock(service, root, resourceName, names));
	}

	return lines;
}

function singleServiceBlock(
	service: Service,
	root: string,
	resourceName: string,
	names: ResourceNames,
): string[] {
	const lines: string[] = [];
	const isStatic = service.kind === "static_site";

	const serviceDir = joinServiceDir(root, service.rootDir);

	lines.push(
		"  - type: web",
		`    name: ${resourceName}`,
		`    runtime: ${isStatic ? "static" : service.runtime}`,
	);
	// Static sites are served from the global CDN — no region field.
	if (!isStatic) {
		lines.push(`    plan: ${factoryConfig.render.servicePlan}`);
		lines.push(`    region: ${factoryConfig.render.region}`);
	}
	lines.push(
		`    rootDir: ${serviceDir}`,
		`    buildCommand: ${service.buildCommand}`,
	);

	// Runs after the build with the service's env vars wired, which makes it
	// the only place a generated app can create its schema. A failure here is
	// a pre_deploy_failed deploy, so a broken migration is a visible failure
	// rather than an app serving an empty database.
	if (service.preDeployCommand) {
		lines.push(`    preDeployCommand: ${service.preDeployCommand}`);
	}
	if (!isStatic && service.startCommand) {
		lines.push(`    startCommand: ${service.startCommand}`);
	}
	if (isStatic && service.staticPublishPath) {
		lines.push(`    staticPublishPath: ${service.staticPublishPath}`);
	}
	if (!isStatic && service.healthCheckPath) {
		lines.push(`    healthCheckPath: ${service.healthCheckPath}`);
	}

	lines.push(
		"    autoDeployTrigger: commit",
		"    buildFilter:",
		"      paths:",
		`        - ${serviceDir}/**`,
	);

	// Wire env vars declared by the manifest.
	const envLines: string[] = [];
	for (const envVar of service.envVars ?? []) {
		if (envVar.fromDatabase) {
			const target =
				(envVar.fromDatabase.name &&
					names.databases.get(envVar.fromDatabase.name)) ||
				names.db;
			if (!target) continue;
			envLines.push(
				`      - key: ${envVar.key}`,
				"        fromDatabase:",
				`          name: ${target}`,
				`          property: ${envVar.fromDatabase.property}`,
			);
		} else if (envVar.fromService) {
			const target = resolveFromServiceName(envVar.fromService.name, names);
			if (!target) continue;
			envLines.push(
				`      - key: ${envVar.key}`,
				"        fromService:",
				`          name: ${target}`,
				"          type: web",
				`          property: ${envVar.fromService.property}`,
			);
		}
	}
	if (envLines.length > 0) {
		lines.push("    envVars:", ...envLines);
	}

	return lines;
}

/**
 * Resolve a service reference in the manifest to a Render resource name. The
 * builder names its own services, so prefer what it declared and fall back to
 * the "api"/"web" roles it may have used instead.
 */
function resolveFromServiceName(
	reference: string,
	names: ResourceNames,
): string | null {
	return (
		names.services.get(reference) ??
		(reference === "api" ? names.api : null) ??
		(reference === "web" ? names.web : null) ??
		names.api ??
		names.web
	);
}

function databaseBlocks(manifest: Manifest, names: ResourceNames): string[] {
	const databases = manifest.databases ?? [];
	if (databases.length === 0) return [];

	const lines = ["databases:"];
	for (const database of databases) {
		const name = names.databases.get(database.name);
		if (!name) continue;
		lines.push(
			`  - name: ${name}`,
			`    plan: ${factoryConfig.render.databasePlan}`,
			`    region: ${factoryConfig.render.region}`,
			`    postgresMajorVersion: "${factoryConfig.render.postgresMajorVersion}"`,
			"    ipAllowList: []",
		);
	}
	return lines.length > 1 ? lines : [];
}

/**
 * Join a manifest-declared rootDir onto the app's repo-relative path. The
 * manifest is agent-authored, so tolerate "." meaning the app directory
 * itself and a rootDir that already repeats the app path.
 */
function joinServiceDir(root: string, rootDir: string): string {
	const cleaned = rootDir.replace(/^\.\/+/, "").replace(/\/+$/, "");
	if (!cleaned || cleaned === ".") return root;
	if (root.endsWith(`/${cleaned}`) || root === cleaned) return root;
	return `${root}/${cleaned}`;
}

function oneLine(value: string): string {
	return value.replace(/\s+/g, " ").slice(0, 160);
}
